import mongoose, { Document, Schema } from 'mongoose';

// Define structure for conversation turns
interface IMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

// Define TypeScript structure representing a Trip in the system
export interface ITrip extends Document {
  userId: mongoose.Types.ObjectId;
  sessionId: string;
  status: 'DRAFT' | 'PLANNED' | 'CONFIRMED' | 'CANCELLED';
  input: {
    destination?: string;
    origin?: string;
    start_date?: string;
    end_date?: string;
    travelers?: number;
    budget_inr?: number;
    interests?: string[];
  };
  weather?: any;         // Structured weather data cache
  transport?: any;       // Selected travel route options
  accommodation?: any;   // Selected hotel arrangements
  activities?: any;      // Target sight-seeing plans
  local_transport?: any; // Cab/fare estimations
  budget?: any;          // Structured breakdown calculations
  itinerary?: any;       // Day-by-day itinerary JSON
  booking?: {
    refs?: any;          // Reference codes from mocks
    confirmed_at?: Date | null;
  };
  formattedPlan?: string; // Markdown summary generated by Coordinator LLM
  conversationHistory: IMessage[]; // Stored chat turns to preserve context
  createdAt: Date;
  updatedAt: Date;
}

const TripSchema = new Schema<ITrip>(
  {
    userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    sessionId: { type: String, required: true, index: true },
    status: {
      type: String,
      enum: ['DRAFT', 'PLANNED', 'CONFIRMED', 'CANCELLED'],
      default: 'DRAFT',
      index: true
    },
    input: {
      destination: { type: String, trim: true },
      origin: { type: String, trim: true },
      start_date: { type: String },
      end_date: { type: String },
      travelers: { type: Number },
      budget_inr: { type: Number },
      interests: [{ type: String }]
    },
    // We use Schema.Types.Mixed (flexible JSON) because sub-agent structural formats
    // can evolve, allowing loose, scalable payloads.
    weather: { type: Schema.Types.Mixed, default: {} },
    transport: { type: Schema.Types.Mixed, default: {} },
    accommodation: { type: Schema.Types.Mixed, default: {} },
    activities: { type: Schema.Types.Mixed, default: {} },
    local_transport: { type: Schema.Types.Mixed, default: {} },
    budget: { type: Schema.Types.Mixed, default: {} },
    itinerary: { type: Schema.Types.Mixed, default: {} },
    booking: {
      refs: { type: Schema.Types.Mixed, default: {} },
      confirmed_at: { type: Date, default: null }
    },
    formattedPlan: { type: String, default: '' },
    conversationHistory: [
      {
        role: { type: String, enum: ['user', 'assistant', 'system'], required: true },
        content: { type: String, required: true }
      }
    ]
  },
  { timestamps: true }
);

export default mongoose.model<ITrip>('Trip', TripSchema);
