import mongoose, { Document } from 'mongoose';

export interface IMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface ITrip extends Document {
  userId: mongoose.Types.ObjectId;
  sessionId: string;
  status: 'DRAFT' | 'PLANNED' | 'CONFIRMED' | 'CANCELLED';
  input: {
    destination?: string;
    origin?: string;
    start_date?: string;
    end_date?: string;
    travelers?: number;
    budget_inr?: number;
    interests?: string[];
    duration_days?: number;
    max_price_per_night?: number;
  };
  weather?: any;         // Structured weather data cache
  transport?: any;       // Selected travel route options
  accommodation?: any;   // Selected hotel arrangements
  activities?: any;      // Target sight-seeing plans
  local_transport?: any; // Cab/fare estimations
  budget?: any;          // Structured breakdown calculations
  itinerary?: any;       // Day-by-day itinerary JSON
  booking?: {
    refs?: any;          // Reference codes from mocks
    confirmed_at?: Date | null;
  };
  formattedPlan?: string; // Markdown summary generated by Coordinator LLM
  conversationHistory: IMessage[]; // Stored chat turns to preserve context
  createdAt: Date;
  updatedAt: Date;
}

export interface TripContext {
  sessionId: string;
  userId: string;
  status: 'DRAFT' | 'PLANNED' | 'CONFIRMED' | 'CANCELLED';
  input: {
    destination?: string;
    origin?: string;
    start_date?: string;
    end_date?: string;
    travelers?: number;
    budget_inr?: number;
    interests?: string[];
    duration_days?: number;
    max_price_per_night?: number;
  };
  weather?: any;
  transport?: any;
  accommodation?: any;
  activities?: any;
  budget?: any;
  itinerary?: any;
  local_transport?: any;
  booking?: any;
  formattedPlan?: string;
  conversationHistory: Array<{ role: string; content: string }>;
}

export interface PlannerAgentResult {
  context: TripContext;
  status: 'NEEDS_INFO' | 'PLANNED' | 'ERROR';
  clarifyingQuestion?: string;
  plan?: string;
  budgetFeasible?: boolean;
  budgetAlternatives?: string[];
}

export interface PlannerServiceResult {
  status: 'NEEDS_INFO' | 'PLANNED' | 'ERROR';
  clarifyingQuestion?: string;
  tripId?: string;
  plan?: string;
  context?: TripContext;
  budgetFeasible?: boolean;
  budgetAlternatives?: string[];
}
